server:
    port: 8081

spring:
    batch:
        job:
            names: ${job.name:NONE}
    datasource:
        driver-class-name: org.h2.Driver
    sql:
        init:
            data-locations: classpath:person.sql
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
