spring:
    datasource:
        hikari:
            jdbc-url: jdbc:mysql://127.0.0.1:3306/spring_batch?characterEncoding=UTF-8&serverTimezone=Asia/Seoul
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: root
            password: 1111
    batch:
        jdbc:
            initialize-schema: never
