spring:
    batch:
        job:
            names: ${job.name:itemWriterJob}
    datasource:
        driver-class-name: org.h2.Driver
    sql:
        init:
            data-locations: classpath:person.sql
