spring:
    datasource:
        hikari:
            jdbc-url: jdbc:mysql://127.0.0.1:3306/pass_batch?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&rewriteBatchedStatements=true
            driver-class-name: com.mysql.cj.jdbc.Driver
            username: root
            password: 1111
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
    batch:
        jdbc:
            initialize-schema: always

logging:
    level:
        org.hibernate.type.descriptor.sql: debug
